name: project
channels:
- pytorch
- defaults
dependencies:
- python==3.12.9
- pip
- pip:
  - torch
  - torchvision
  - wandb
  - ipykernel
  - fasttext
  - einops
  - easyocr
  - opencv-python-headless
  - numpy
  - matplotlib
  - tqdm
